.travis.yml
=> Initial travis setup.

.circleci/config.yml, c/io_tests.c, c/kastore.c, c/malloc_tests.c, c/meson.build, c/tests.c
=> Tests for malloc failures.

.travis.yml, appveyor.yml, c/kastore.c, python/kastore/__init__.py, python/requirements/development.txt
=> Fix 32 bit build issue.

.circleci/config.yml, python/release/build-wheels.sh, python/release/docker-build-wheels.sh, python/release/wheelhouse/README
=> Infrastructure for building release wheels.

.travis.yml, appveyor.yml, docs/rtd_requirements.txt, python/_kastoremodule.c, python/kastore/__init__.py, python/kastore/__main__.py, python/kastore/cli.py, python/kastore/exceptions.py, python/kastore/store.py, python/make_standard_files.py, python/requirements/development.txt, python/setup.py, python/stress_lowlevel.py, python/tests/test_cli.py, python/tests/test_errors.py, python/tests/test_file_format.py, python/tests/test_interface.py, python/tests/test_standard_files.py, python/tests/test_storage.py
=> Remove support for Python 2

appveyor.yml, c/kastore.c, c/kastore.h, c/tests.c
This should cover the changes you need @bhaller. I've changed the name to "own_put" rather than "take" --- I just seems too confusing to me to have a completely different name for an almost identical operation (which we'd implement with a flag to put, if we could).
I'm open to better ideas though... any thoughts @petrelharp?
=> Take ownership of array buffer

appveyor.yml
=> Update conda in appveyor build

.readthedocs.yml, docs/rtd_requirements.txt
=> Update RTD configuration.

appveyor.yml, python/MANIFEST.in, python/tests/test_fileobj.py
=> Enable nosetests on Appveyor.

python/setup.py
Fixes #113 
I've gone with `Development Status :: 5 - Production/Stable` as we don't foresee any major future development. Next step is `Development Status :: 6 - Mature` so this feels right.
=> Update trove classifier

python/setup.py
=> Add license and platforms to setup.py

c/kastore.c, c/tests.c, python/kastore/store.py, python/tests/test_file_format.py
=> Fix EOF semantics.

.github/workflows/lint.yml, .github/workflows/wheels.yml, docker/buildwheel.sh, docker/shared.env, docs/development.rst, python/requirements/CI/tests/requirements.txt, python/setup.py
=> Build wheels in github action, upload to pypi on tag

docs/development.rst, python/kastore/__init__.py
=> Docs update

python/setup.py
=> Removed oldest-supported-numpy from setup.py

docs/python-api.rst
As discussed in https://github.com/tskit-dev/pyslim/issues/84#issuecomment-636725968
=> modify store example

.github/workflows/lint.yml, python/Makefile
The suppressed error is something that has to happen in the Python C Api
=> Fix development makefile to allow compilation.

c/kastore.c
=> Fix warning on gcc 4.8.5

.github/workflows/wheels.yml, c/meson.build, docker/shared.env
These `nose`s slipped through.
=> Fix wheel building tests

.mergify.yml
https://blog.mergify.com/strict-mode-deprecation/
=> Update mergify config for deprecations

.circleci/config.yml, c/kastore.c, c/kastore.h
=> Seperate allocs for KAS_READ_ALL

c/kastore.c, c/kastore.h, c/tests.c
=> KAS_GET_TAKES_OWNERSHIP

c/CHANGELOG.rst, c/kastore.c, c/kastore.h, c/tests.c
Fixes #180 
Still needs docs so draft, had to break up the put operation a bit, but I think this makes sense.
=> Implement KAS_PUT_BORROWS_ARRAY

c/kastore.c
=> Fix error string
